var data = {"items":[
	{"title":"Horizon: The defenders of anonymity on the internet", "date":"2 September 2014", "author":"Mike Radford", "description":"You may not realise it, but every time you open up your laptop or switch on your phone, you are at the heart of one of the greatest battles now taking place in our midst - what shape will the internet take in the future, and what role will anonymity play in deciding it?", "image":"_77329884_e833e7ab-5522-4383-853d-8256bdc01eb1.jpg", "link":"http://www.bbc.com/news/technology-29032399"},
	{"title":"Fifa World Cup 'hits the poorest hardest'", "date":"7 September 2014", "author":"Bill Wilson", "description":"A leading international charity is calling for major sports governing bodies Fifa and the International Olympic Committee (IOC) to change their way of doing business around their showcase global events.", "image":"_77382294_77380025.jpg", "link":"http://www.bbc.com/news/business-28881952"},
	{"title":"Google plans debates on 'right to be forgotten'", "date":"8 September 2014", "author":"BBC - Technology", "description":"Google is holding seven public meetings across Europe to debate issues raised by the 'right to be forgotten' ruling.", "image":"_77450435_152807959.jpg", "link":"http://www.bbc.com/news/technology-28344705"},
	{"title":"'Smart' chopsticks unveiled in China", "date":"4 September 2013", "author":"BBC - Technology", "description":"Electronic chopsticks that can detect whether food is unsafe to eat have been unveiled by Chinese tech company Baidu.", "image":"_77371397_2ea50a19-3e63-483b-98cc-ea22eca9e3c9.jpg", "link":"http://www.bbc.com/news/technology-29062509"},
	{"title":"'Black market' for stolen smartphones exposed", "date":"14 April 2013", "author":"Guy Lynn and Ed Davey", "description":"A black market of shops and traders willing to deal in stolen smartphones has been exposed by a BBC London undercover investigation.", "image":"_74183940_screenshot2014-04-10at17.46.44.png", "link":"http://www.bbc.com/news/uk-england-london-26979061"},
	{"title":"Microsoft phones get flash trick for low light snaps", "date":"4 September 2013", "author":"Leo Kelion", "description":"Microsoft's Lumia smartphones are getting a new feature designed to improve the quality of photos taken in low-light settings.", "image":"_77371849_a142b144-f61f-478c-bd4e-b189d915b76c.jpg", "link":"http://www.bbc.com/news/technology-29059632"},
	{"title":"China: Shang or Zhou dynasty sword found in Jiangsu", "date":"8 September 2014", "author":"News from Elsewhere...", "description":"A Chinese boy has made the discovery of a lifetime by stumbling across a 3,000-year-old bronze sword in a river in Jiangsu Province.", "image":"_77446266_chinasword_anhuitv.jpg", "link":"http://www.bbc.com/news/blogs-news-from-elsewhere-29108764"},
	{"title":"Scottish independence: Pound falls after referendum poll", "date":"8 September 2014", "author":"BBC - UK", "description":"The value of the pound has fallen in the wake of an opinion poll which suggested the pro-UK campaign had lost its lead ahead of the Scottish independence referendum.", "image":"_77451281_darlingoncampaigntrail.jpg", "link":"http://www.bbc.com/news/uk-scotland-29105565"},
	{"title":"The secret to acing exams", "date":"5 September 2014", "author":"William Poundstone", "description":"In tests that offer a choice of answers, you can exploit hidden patterns to get full marks if you know how, says William Poundstone.", "image":"p0263qts.jpg", "link":"http://www.bbc.com/future/story/20140905-the-secret-to-acing-exams"},
	{"title":"Super Organism Engulfing Earth", "date":"2 July 2014", "author":"Gaia Vince", "description":"Is our species evolving into something new? Gaia Vince makes the provocative argument that humanity is transforming, and it is already having a huge effect on life on our planet.", "image":"p021z10m.jpg", "link":"http://www.bbc.com/future/story/20140701-the-superorganism-engulfing-earth"}
]};